//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStoreCollectionWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string Platform { get; set; }
        public string UUID { get; set; }
        public string Version { get; set; }
        public string Token { get; set; }
        public string AppVersion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ShopRegistration ShopRegistration { get; set; }
        public virtual StoreRegistration StoreRegistration { get; set; }
    }
}
