//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStoreCollectionWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InStoreCollectionEntities : DbContext
    {
        public InStoreCollectionEntities()
            : base("name=InStoreCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<DeviceInfo> DeviceInfoes { get; set; }
        public virtual DbSet<Parcel> Parcels { get; set; }
        public virtual DbSet<ParcelGroup> ParcelGroups { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopRegistration> ShopRegistrations { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreGroup> StoreGroups { get; set; }
        public virtual DbSet<StoreRegistration> StoreRegistrations { get; set; }
    }
}
