//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStoreCollectionWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public int Id { get; set; }
        public int ParcelGroupId { get; set; }
        public Nullable<System.DateTime> DateScannedIntoStore { get; set; }
        public Nullable<System.DateTime> DateCollectedByCustomer { get; set; }
        public Nullable<System.DateTime> DateReturnedToStore { get; set; }
        public string TrackingNumber { get; set; }
        public string Status { get; set; }
        public string CollectionType { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public int ParcelNumber { get; set; }
    
        public virtual ParcelGroup ParcelGroup { get; set; }
    }
}
