//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStoreCollectionWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParcelGroup()
        {
            this.Parcels = new HashSet<Parcel>();
        }
    
        public int Id { get; set; }
        public int CollectionPointId { get; set; }
        public string InvoiceNumber { get; set; }
        public string PersonName { get; set; }
        public string PersonPhone { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<decimal> AgeInHours { get; set; }
        public Nullable<int> IsMobilePhoneNumber { get; set; }
        public string Pin { get; set; }
        public string CustomerReference { get; set; }
        public int ParcelCount { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcel> Parcels { get; set; }
    }
}
